# Generated by Django 5.1.2 on 2024-11-07 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='workouts.category')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('goal', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WorkoutItem',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True, null=True)),
                ('sets', models.PositiveIntegerField()),
                ('repetitions', models.PositiveIntegerField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('rest', models.DurationField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workouts.workout')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
    ]
